
## Preparing data

In [13]:

from scipy.io import arff
import pandas as pd

## Loading the dataset
dataset = arff.loadarff('EEG_Eye_State.arff') 
dframe = pd.DataFrame(dataset[0])

#veryfy columns
dframe.head()

,AF3,F7,F3,FC5,T7,P7,O1,O2,P8,T8,FC6,F4,F8,AF4,eyeDetection
0,4329.23,4009.23,4289.23,4148.21,4350.26,4586.15,4096.92,4641.03,4222.05,4238.46,4211.28,4280.51,4635.90,4393.85,0
1,4324.62,4004.62,4293.85,4148.72,4342.05,4586.67,4097.44,4638.97,4210.77,4226.67,4207.69,4279.49,4632.82,4384.10,0
2,4327.69,4006.67,4295.38,4156.41,4336.92,4583.59,4096.92,4630.26,4207.69,4222.05,4206.67,4282.05,4628.72,4389.23,0
3,4328.72,4011.79,4296.41,4155.90,4343.59,4582.56,4097.44,4630.77,4217.44,4235.38,4210.77,4287.69,4632.31,4396.41,0
4,4326.15,4011.79,4292.31,4151.28,4347.69,4586.67,4095.90,4627.69,4210.77,4244.10,4212.82,4288.21,4632.82,4398.46,0

In [15]:
#verify row size
dframe.count

#How to pre-process the data?
# create a vector of size 14
embed_vector = []
# select output column - eyeDetection
actual_output = []

for i in dframe.column:
    actual_output.append(dataset.columns[i])

AttributeError: 'DataFrame' object has no attribute 'column'